# Path to your oh-my-zsh configuration.
ZSH=$HOME/.oh-my-zsh

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
ZSH_THEME="magnet/miloshadzic-3-path"

# Set to this to use case-sensitive completion
# CASE_SENSITIVE="true"

# Plugins
plugins=(%(plugins)s)

source $ZSH/oh-my-zsh.sh

# Customize to your needs...

# ~/bin in PATH
if [[ -d ~/bin ]]; then
    export PATH=$PATH:~/bin
fi

# keep history file between sessions
DIRSTACKSIZE=15
HISTSIZE=10000000
SAVEHIST=10000000
HISTFILE=~/.zsh_history

# more verbose file utilities
alias mv="mv -vi"
alias cp="cp -vai"
alias rm="rm -v"
alias chmod="chmod -v"
alias chown="chown -v"

# dircolors
if [[ -f ~/.dircolors ]]; then
    eval `dircolors -b ~/.dircolors`
fi

# cdargs
if [[ -e /usr/share/doc/cdargs/examples/cdargs-bash.sh ]]; then
    . /usr/share/doc/cdargs/examples/cdargs-bash.sh
fi

# cd + virtualenv activation + ls
function cd() {
    # default cd
    builtin cd $1;

    # virtualenv activation
    GIT_DIR=`git rev-parse --git-dir 2> /dev/null`
    if [[ $? == 0 ]]
    then
        if [[ -f $GIT_DIR/../.env/bin/activate ]]
        then
            . $GIT_DIR/../.env/bin/activate
        else
            if [[ $VIRTUAL_ENV != "" ]]
            then
                deactivate
            fi
        fi
    else
        if [[ $VIRTUAL_ENV != "" ]]
        then
            deactivate
        fi
    fi

    # optional ls
    # ls
}

# grep recursive through all
function grepr(){
    grep "$*" -Ir *
}

# fabric autocomplete
if [[ -f ~/.zsh_fab ]]; then
    . ~/.zsh_fab
fi

# default user (prompt)
DEFAULT_USER=%(user)s

zstyle ':completion:*' special-dirs true

# default editor
export EDITOR=%(default_editor)s

# disable correction
unsetopt correct_all
