# Path to your oh-my-zsh configuration.
ZSH=$HOME/.oh-my-zsh

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
ZSH_THEME="miloshadzic-3-path"

# local settings
if [ ! -d ~/.zsh ]; then
    mkdir ~/.zsh
fi

if [[ ! -f ~/.zsh/zshrc.zsh ]]; then
    touch ~/.zsh/zshrc.zsh
fi
. ~/.zsh/zshrc.zsh

# dircolors
if [[ -f ~/.dircolors ]]; then
    eval `dircolors -b ~/.dircolors`
fi

# Ignore duplicate entries in zsh history
export HISTCONTROL=erasedups

# Set to this to use case-sensitive completion
# CASE_SENSITIVE="true"

# Plugins
plugins=(%(plugins)s)

source $ZSH/oh-my-zsh.sh

# Customize to your needs...

# ~/bin in PATH
if [[ -d ~/bin ]]; then
    export PATH=$PATH:~/bin
fi

# keep history file between sessions
DIRSTACKSIZE=15
HISTSIZE=10000000
SAVEHIST=10000000
HISTFILE=~/.zsh_history

# more verbose file utilities
alias mv="mv -vi"
alias cp="cp -vai"
alias rm="rm -v"
alias chmod="chmod -v"
alias chown="chown -v"

# aliases
if [[ ! -f ~/.zsh/aliases.zsh ]]; then
    touch ~/.zsh/aliases.zsh
fi
. ~/.zsh/aliases.zsh

# cdargs
if [[ -e /usr/share/doc/cdargs/examples/cdargs-bash.sh ]]; then
    . /usr/share/doc/cdargs/examples/cdargs-bash.sh
fi

# fabric autocomplete
if [[ -f ~/.zsh_fab ]]; then
    . ~/.zsh_fab
fi

# default user (prompt)
DEFAULT_USER=%(user)s

zstyle ':completion:*' special-dirs true

# default editor
export EDITOR=%(default_editor)s

# disable correction
unsetopt correct_all
